//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Magazine.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agendadas.
        /// </summary>
        public static string AddDiaryMagazinesDiaryAgenda {
            get {
                return ResourceManager.GetString("AddDiaryMagazinesDiaryAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar a Favoritos.
        /// </summary>
        public static string AddFavorite {
            get {
                return ResourceManager.GetString("AddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atras.
        /// </summary>
        public static string BackView {
            get {
                return ResourceManager.GetString("BackView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Favorito.
        /// </summary>
        public static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtro.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        public static string IHClear {
            get {
                return ResourceManager.GetString("IHClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revistas Encontradas.
        /// </summary>
        public static string IHJournalsFound {
            get {
                return ResourceManager.GetString("IHJournalsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre revista, ISSN o Nombre Editor.
        /// </summary>
        public static string IHMarkSearch {
            get {
                return ResourceManager.GetString("IHMarkSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string IHSearch {
            get {
                return ResourceManager.GetString("IHSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INICIO.
        /// </summary>
        public static string IndexHome {
            get {
                return ResourceManager.GetString("IndexHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca.
        /// </summary>
        public static string IndexHomeAcerca {
            get {
                return ResourceManager.GetString("IndexHomeAcerca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Revista.
        /// </summary>
        public static string IndexHomeBuscar {
            get {
                return ResourceManager.GetString("IndexHomeBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string IndexHomeCerrarSesion {
            get {
                return ResourceManager.GetString("IndexHomeCerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        public static string IndexHomeContactos {
            get {
                return ResourceManager.GetString("IndexHomeContactos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string IndexHomeIniciarSesion {
            get {
                return ResourceManager.GetString("IndexHomeIniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string IndexHomeResgistrarse {
            get {
                return ResourceManager.GetString("IndexHomeResgistrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Revistas Favoritas.
        /// </summary>
        public static string IndexMagazineMyRevistas {
            get {
                return ResourceManager.GetString("IndexMagazineMyRevistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ISSN.
        /// </summary>
        public static string ISSN {
            get {
                return ResourceManager.GetString("ISSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cobertura.
        /// </summary>
        public static string MCoverage {
            get {
                return ResourceManager.GetString("MCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Ing..
        /// </summary>
        public static string MDataIn {
            get {
                return ResourceManager.GetString("MDataIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string MDescription {
            get {
                return ResourceManager.GetString("MDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Favorita.
        /// </summary>
        public static string MFavorite {
            get {
                return ResourceManager.GetString("MFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REVISTAS FAVORITAS.
        /// </summary>
        public static string MgzJournalsFavorites {
            get {
                return ResourceManager.GetString("MgzJournalsFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indice.
        /// </summary>
        public static string MIndex {
            get {
                return ResourceManager.GetString("MIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ISSN.
        /// </summary>
        public static string MIssn {
            get {
                return ResourceManager.GetString("MIssn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realice una búsqueda de una revista favorita..
        /// </summary>
        public static string MnsHomeFilterMgz {
            get {
                return ResourceManager.GetString("MnsHomeFilterMgz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La revista ya ha sido agendada..
        /// </summary>
        public static string MnsMgzStoreExist {
            get {
                return ResourceManager.GetString("MnsMgzStoreExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La revista ya ha sido almacenada como favorita..
        /// </summary>
        public static string MnsMgzStoreExistFavorite {
            get {
                return ResourceManager.GetString("MnsMgzStoreExistFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardado Correctamente..
        /// </summary>
        public static string MnsMgzSucessSave {
            get {
                return ResourceManager.GetString("MnsMgzSucessSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revista Agendada.
        /// </summary>
        public static string MnsMgzSucessStoreVirtual {
            get {
                return ResourceManager.GetString("MnsMgzSucessStoreVirtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones.
        /// </summary>
        public static string MOptions {
            get {
                return ResourceManager.GetString("MOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alcance.
        /// </summary>
        public static string Mscope {
            get {
                return ResourceManager.GetString("Mscope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado datos..
        /// </summary>
        public static string MsnMgzErrorNotFoundData {
            get {
                return ResourceManager.GetString("MsnMgzErrorNotFoundData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se a podido agendar..
        /// </summary>
        public static string MsnMgzErrorStoredVirtual {
            get {
                return ResourceManager.GetString("MsnMgzErrorStoredVirtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay revistas agendadas..
        /// </summary>
        public static string MsnMgzNotStored {
            get {
                return ResourceManager.GetString("MsnMgzNotStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editor.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tip.Pub..
        /// </summary>
        public static string PubType {
            get {
                return ResourceManager.GetString("PubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string RegDate {
            get {
                return ResourceManager.GetString("RegDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agendar.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tema.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agenda de Revistas.
        /// </summary>
        public static string TituloApp {
            get {
                return ResourceManager.GetString("TituloApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Panel de Control.
        /// </summary>
        public static string TituloPanelAdmin {
            get {
                return ResourceManager.GetString("TituloPanelAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agendar Revistas.
        /// </summary>
        public static string TituloPanelUser {
            get {
                return ResourceManager.GetString("TituloPanelUser", resourceCulture);
            }
        }
    }
}
