//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Magazine.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agendadas.
        /// </summary>
        public static string AddDiaryMagazinesDiaryAgenda {
            get {
                return ResourceManager.GetString("AddDiaryMagazinesDiaryAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INICIO.
        /// </summary>
        public static string IndexHome {
            get {
                return ResourceManager.GetString("IndexHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca.
        /// </summary>
        public static string IndexHomeAcerca {
            get {
                return ResourceManager.GetString("IndexHomeAcerca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Revista.
        /// </summary>
        public static string IndexHomeBuscar {
            get {
                return ResourceManager.GetString("IndexHomeBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string IndexHomeCerrarSesion {
            get {
                return ResourceManager.GetString("IndexHomeCerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        public static string IndexHomeContactos {
            get {
                return ResourceManager.GetString("IndexHomeContactos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string IndexHomeIniciarSesion {
            get {
                return ResourceManager.GetString("IndexHomeIniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registre.
        /// </summary>
        public static string IndexHomeResgistrarse {
            get {
                return ResourceManager.GetString("IndexHomeResgistrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Revistas Favoritas.
        /// </summary>
        public static string IndexMagazineMyRevistas {
            get {
                return ResourceManager.GetString("IndexMagazineMyRevistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realice una búsqueda de una revista favorita..
        /// </summary>
        public static string MnsHomeFilterMgz {
            get {
                return ResourceManager.GetString("MnsHomeFilterMgz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La revista ya ha sido agendada..
        /// </summary>
        public static string MnsMgzStoreExist {
            get {
                return ResourceManager.GetString("MnsMgzStoreExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardado Correctamente..
        /// </summary>
        public static string MnsMgzSucessSave {
            get {
                return ResourceManager.GetString("MnsMgzSucessSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revista Agendada.
        /// </summary>
        public static string MnsMgzSucessStoreVirtual {
            get {
                return ResourceManager.GetString("MnsMgzSucessStoreVirtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se a podido agendar..
        /// </summary>
        public static string MsnMgzErrorStoredVirtual {
            get {
                return ResourceManager.GetString("MsnMgzErrorStoredVirtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay revistas agendadas..
        /// </summary>
        public static string MsnMgzNotStored {
            get {
                return ResourceManager.GetString("MsnMgzNotStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agenda de Revistas.
        /// </summary>
        public static string TituloApp {
            get {
                return ResourceManager.GetString("TituloApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Panel de Control.
        /// </summary>
        public static string TituloPanelAdmin {
            get {
                return ResourceManager.GetString("TituloPanelAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agendar Revistas.
        /// </summary>
        public static string TituloPanelUser {
            get {
                return ResourceManager.GetString("TituloPanelUser", resourceCulture);
            }
        }
    }
}
