//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magazine
    {
        public int Id { get; set; }
        public string Country { get; set; }
        public string Subjec { get; set; }
        public string Publisher { get; set; }
        public string PublicationType { get; set; }
        public string ISSN { get; set; }
        public string Coverage { get; set; }
        public string Scope { get; set; }
        public string Quartiles { get; set; }
        public string SJR { get; set; }
        public string CitationsPerDocument { get; set; }
        public string Cites { get; set; }
        public string InternationalCollaboration { get; set; }
        public string DocumentsNoncitable { get; set; }
        public string DocumentsUncited { get; set; }
        public string TotalCites { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
