//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MagazineModels
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Imagen { get; set; }
        public string Hindexnumber { get; set; }
        public string Hindexlegend { get; set; }
        public string Url { get; set; }
        public string Country { get; set; }
        public string Subjec { get; set; }
        public string Publisher { get; set; }
        public string PublicationType { get; set; }
        public string ISSN { get; set; }
        public string Coverage { get; set; }
        public string Scope { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
        public Nullable<bool> Favorite { get; set; }
        public string QuartilesDesc { get; set; }
        public string SJRDesc { get; set; }
        public string CitationsPerDocumentDesc { get; set; }
        public string CitesDesc { get; set; }
        public string InternationalCollaborationDesc { get; set; }
        public string DocumentsNoncitableDesc { get; set; }
        public string DocumentsUncitedDesc { get; set; }
        public string TotalCitesDesc { get; set; }
        public string Quartiles { get; set; }
        public string SJR { get; set; }
        public string CitationsPerDocument { get; set; }
        public string Cites { get; set; }
        public string InternationalCollaboration { get; set; }
        public string DocumentsNoncitable { get; set; }
        public string DocumentsUncited { get; set; }
        public string TotalCites { get; set; }
        public string UserId { get; set; }
    }
}
